import AuthModal from "@/components/AuthModal.tsx/AuthModal";
import useAuth from "@/hooks/useAuth";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

export default function Home() {
  const router = useRouter();
  const { userType, login } = useAuth();
  const [modalOpen, setModalOpen] = useState(false);

  useEffect(() => {
    if (userType === "recruiter") router.replace("/recruiter/jobs");
    else if (userType === "user") router.replace("/user/jobs");
    else setModalOpen(true);
  }, [userType]);

  const handleSelect = (type: "recruiter" | "user") => {
    login(type);
    if (type === "recruiter") router.push("/recruiter/jobs");
    else router.push("/user/jobs");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthModal open={modalOpen} onSelect={handleSelect} />;
    </>
  );
}
